### ISSUE TITLE
Поменять текст на главной

### ISSUE THREAD

**Issue by murad1986** [qwe522y/billboard05#10]
**Интерактивная карта**
Выбрать нужное вам рекламное место проще и удобнее вместе с интерактивной картой.

**Актуальные данные**
Мы и наши партнеры стараемся каждый день обновлять данные на нашем сайте,
чтоб на каждый момент времени информация представленная на сайте была верной.

**Полное оформление**
Мы помогаем вам на одном сайте найти и забронировать рекламную площадь, в добавок поможем распечатать баннер.

**Comment by qwe522y** [comment]
текст ужасен, заменил на:
Мы и наши партнеры стараемся каждый день обновлять данные на нашем сайте, чтобы вы всегда имели самую актуальную информацию
и
Мы поможем вам на не только найти и забронировать рекламную площадь, но и распечатать баннер соответствующего формата
